### ISSUE TITLE
dev.zip can not download from official website

### ISSUE THREAD

**Issue by dingye18** [tencent-alchemy/Alchemy#1]
It looks like we can't download dev.zip file from website [Alchemy Contest](https://alchemy.tencent.com/) 
![image](https://user-images.githubusercontent.com/13417572/58468588-69089080-8170-11e9-8a82-3934d8d03c04.png)

**Comment by dingye18** [comment]
After tried many times, I solved it......

**Comment by xptree** [comment]
Thanks for letting us know. We have fixed it.
