### ISSUE TITLE
I did not receive verification email

### ISSUE THREAD

**Issue by dingye18** [tencent-alchemy/Alchemy#10]
When I signed up in new Alchemy Contest Codalab, I tried many email account. But  I did not receive any verification email for now, spam folder was searched already.
![image](https://user-images.githubusercontent.com/13417572/62435860-38486700-b770-11e9-958f-01a143c2979c.png)

**Comment by mindon** [comment]
something is wrong with the e-mail SMTP service,  you could  try sign in directly right now.
