### ISSUE TITLE
Your code failed to read the dataset.

### ISSUE THREAD

**Issue by Mengjintao** [tencent-alchemy/Alchemy#13]
This is the training data downloaded with your script. 

> (Alchemy) xxx@xxx-Intel:~/Desktop/Alchemy$ ls data-bin/raw/dev/
dev_target.csv  sdf

These files below are the data your code ask for with torch_geometric: 
>['data-bin/raw/dev/sdf', 'data-bin/raw/dev/train.csv']

Your code just failed with the following words when runing python2.7 pyg/mpnn.py:

>Traceback (most recent call last):
  File "pyg/mpnn.py", line 48, in <module>
    train_dataset = TencentAlchemyDataset(root='data-bin', mode='dev', transform=transform).shuffle()
  File "/home/jtmeng/Desktop/Alchemy/pyg/Alchemy_dataset.py", line 33, in __init__
    super(TencentAlchemyDataset, self).__init__(root, transform, pre_transform, pre_filter)
  File "/usr/local/lib/python2.7/dist-packages/torch_geometric/data/in_memory_dataset.py", line 56, in __init__
    pre_filter)
  File "/usr/local/lib/python2.7/dist-packages/torch_geometric/data/dataset.py", line 82, in __init__
    self._download()
  File "/usr/local/lib/python2.7/dist-packages/torch_geometric/data/dataset.py", line 119, in _download
    self.download()
  File "/home/jtmeng/Desktop/Alchemy/pyg/Alchemy_dataset.py", line 45, in download
    raise NotImplementedError('please download and unzip dataset from %s, and put it at %s' % (_urls[self.mode], self.raw_dir))
NotImplementedError: please download and unzip dataset from https://alchemy.tencent.com/data/dev.zip, and put it at data-bin/raw.

Can you help to fix your code or script to resolve the above issues? Thanks.

**Comment by geekinglcq** [comment]
Hi, the `download` function here is just a placeholder. You could solve the problem with simply do the following change:  

In `pyg/Alchemy_dataset.py:L53`.  

From   
```py 
def download(self):
    raise NotImplementedError('please download and unzip dataset from %s, and put it at %s' % (_urls[self.mode], self.raw_dir))
```
To    
```py 
def download(self):
    pass
```

**Comment by mufeili** [comment]
@geekinglcq 

With your suggested modification, I got

> FileNotFoundError: [Errno 2] File b'data-bin/raw/dev/train.csv' does not exist: b'data-bin/raw/dev/train.csv'

I assume `train.csv` is now renamed as `dev_target.csv`?
