### ISSUE TITLE
Name of QM properties in dataset

### ISSUE THREAD

**Issue by sha256feng** [tencent-alchemy/Alchemy#2]
What are the specific QM property names for the 12 properties listed in the CSV file?

**Comment by xptree** [comment]
These 12 properties are the same ones calculated in the QM9 dataset. We prefer not to disclose this information (while the contest is still going on), as these properties can also be computed with standard quantum chemistry packages.  Thank you for your understanding.

**Comment by sha256feng** [comment]
Thank you!
