### ISSUE TITLE
Codalab server is down

### ISSUE THREAD

**Issue by dingye18** [tencent-alchemy/Alchemy#6]
It looks like codalab server is down, and the backup website which provided by administrator of Codalab [Codalab-new](https://competitions-new.codalab.org/my/) had lost the data for Alchemy-contest competitions.
So for organizers of alchemy-contest, where we should submit our latest model results? Or just wait......

**Comment by GuangyongChen** [comment]
It seems that codalab server is a little fragile, so that we decide to implement the codalab service on our own server. We will email all contestants to move to our own website once we finished.

Best Regards
Organizers of alchemy-contest
