### ISSUE TITLE
Competition Submission Issue

### ISSUE THREAD

**Issue by haonan3** [tencent-alchemy/Alchemy#7]
Hi,

The result submission of the competition website seems out of service recently. Is there an alternative way to submit my new result and get updates of the leaderboard?

Thanks.
Haonan Wang

**Comment by GuangyongChen** [comment]
We have installed codalab service on our own server and will release the service soon (by next week). We encourage contestants to submit the prediction results to our own server now. 

Thanks very much for your patient！We will email all contestants with detailed instructions once we are done!

**Comment by haonan3** [comment]
Thx!
